name: Publish to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    name: Build distribution
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
      - name: Build
        run: uv build
      - name: Check dist
        run: uvx twine check dist/*
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/

  # requires human approval
  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
