name: Python application

on:
  push:
    branches: [ "main", "dev" ]
    tags:
      - "*"
    paths-ignore:
      - docs/**
      - "**.md"
      - .github/workflows/docs.yml
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - docs/**
      - "**.md"
      - .github/workflows/docs.yml

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        env:
          UV_SYSTEM_PYTHON: "1"
        run: uv pip install -e . -r requirements_dev.txt --override override.txt
      - name: Test with pytest
        run: pytest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        env:
          UV_SYSTEM_PYTHON: "1"
        run: uv pip install -e . -r requirements_dev.txt --override override.txt
      - name: Run coverage
        run: |
          coverage erase
          PYTHONPATH=$PYTHONPATH:$(pwd) coverage run --source=spade_llm -m pytest
          coverage xml
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml
          format: cobertura
      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
